# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0002_sagyurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagyurl',
            name='shortcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
